name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        rust: [ stable, nightly ]

    steps:
    - uses: actions/checkout@v3
      with:
        rust-version: ${{ matrix.rust }}
    - name: Format Code
      run: cargo fmt --all
    - name: Clippy Code
      run: cargo clippy --all
    - name: Check Code
      run: cargo check --all
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
